

POST http://{{url}}/api/v1/storage/ls
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzYwNDc4ODcsImp0aSI6InRhbmd0aGlua2VyIiwiaWF0IjoxNzM1OTYxNDg3fQ.RmJ96XR-2PQcBYnPxJrHvtqZqAUXtAwJz8IsybOYdjM

{
  "path" : "/"
}

###

GET http://{{url}}/api/v1/storage/get?filepath=/2024/2024-01-01/IMG_0001.JPG

###

GET http://{{url}}/api/v1/storage/get-thumbnail?width=800&height=400&filepath=/推荐系统优化方案 (1).png


###

GET http://{{url}}/api/v1/storage/download?filepath=/白板文件 (28).png


###

POST http://{{url}}/api/v1/storage/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="main.go"

< ../main.go
--boundary
Content-Disposition: form-data; name="path";

/
--boundary
Content-Disposition: form-data; name="filename";

test-upload-main-1.go
--boundary--
###
