

POST http://{{url}}/api/v1/storage/ls
Content-Type: application/json

{
  "path" : "/"
}

###

GET http://{{url}}/api/v1/storage/get?filepath=/白板文件 (28).png


###

GET http://{{url}}/api/v1/storage/download?filepath=/白板文件 (28).png


###

POST http://{{url}}/api/v1/storage/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="main.go"

< ../main.go
--boundary
Content-Disposition: form-data; name="path";

/internal/
--boundary
Content-Disposition: form-data; name="filename";

test-upload-main.go
--boundary--
###
